[book]
authors = ["Reflow Team"]
language = "en"
multilingual = false
src = "docs"
title = "Reflow Documentation"
description = "Comprehensive documentation for the Reflow workflow automation engine - featuring distributed graph network and multi-graph composition"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/reflow-project/reflow"
edit-url-template = "https://github.com/reflow-project/reflow/edit/main/docs/{path}"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 1

[preprocessor.links]

[preprocessor.index]
