[package]
name = "async_actor"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
reflow_wasm = { path = "../.." }
extism-pdk = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"

[lib]
crate-type = ["cdylib"]