[package]
name = "reflow_wasm"
version = "0.1.0"
edition = "2021"
description = "WebAssembly Actor Development Kit"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
extism-pdk = {version = "1.4.0"}
anyhow = { workspace = true }